# Generated by Django 2.1.5 on 2019-02-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_auto_20190215_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Player')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Owner')),
            ],
        ),
    ]
