# Generated by Django 2.1.5 on 2019-02-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeID', models.IntegerField()),
                ('cap', models.IntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Player')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givers', to='liga.Owner')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Owner')),
            ],
        ),
    ]
