# Generated by Django 2.1.5 on 2019-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ftag',
            field=models.BooleanField(default=False),
        ),
    ]
